apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  labels:
    {{- include "valkey-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - name: http
      port: {{ .Values.app.port }}
      targetPort: http
