apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.valkey.name }}
  labels:
    {{- include "valkey-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: valkey
spec:
  selector:
    app: {{ .Values.valkey.name }}
  ports:
    - name: valkey
      port: {{ .Values.valkey.port }}
      targetPort: valkey
